# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  #- name: Talleres de bioinformática
   # url: '/'
    #weight: 10
  - name: Cursos
    weight: 20
    identifier: courses
  - name: Introsucción a la bioinformática
    PageRef: course/Introsuccion_a_la_bioinformotica/_index.md
    weight: 10
    parent: courses
  - name: Metagenómica
    PageRef: course/Metagenomica/_index.md
    weight: 20
    parent: courses
  - name: Genómica poblacional
    PageRef: course/Genomica_poblacional/_index.md
    weight: 20
    parent: courses
  #- name: Blog
   # PageRef: post/_index.md
  #  weight: 30
  - name: Contact
    PageRef: contact/index.md
    weight: 60
